[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "strata_rs"
version = "0.1.0"

[dependencies]
serde = "0.8.22"
serde_derive = "0.8.22"
serde_json = "0.8.6"

[dependencies.peresil]
path = "../sxd/peresil"
