[package]
authors = ["Jake Goulding <jake.goulding@gmail.com>"]
name = "strata_rs"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.2"
rocket = "0.1.5"
rocket_codegen = "0.1.5"
serde = "0.8.22"
serde_derive = "0.8.22"
serde_json = "0.8.6"

[dependencies.peresil]
path = "../sxd/peresil"

[dependencies.strata]
path = "../strata"
